server:
  port: 8086

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot-dev?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    #driver-class-name: com.mysql.cj.jdbc.Driver