server:
  port: 8888

spring:
  profiles:
    active: dev

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
##1.JAP\u64CD\u4F5C
#  datasource:
#    url: jdbc:mysql://localhost:3306/springboot-dev?useUnicode=true&characterEncoding=utf-8&useSSL=false
#    username: root
#    password: root
#    driver-class-name: com.mysql.jdbc.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
#    database: mysql
#    show-sql: true
