spring:
#  activiti:
#    check-process-definitions: false
#    database-schema-update: true
#    process-definition-location-prefix: classpath:/processes/
#    history-level: full
  profiles:
    active: dev

  main:
    allow-bean-definition-overriding: true