server:
  port: 8086

spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/springboot-pro?useUnicode=true&characterEncoding=utf-8&useSSL=false
#    username: root
#    password: root
#    driver-class-name: com.mysql.jdbc.Driver
  datasource:
    primary:
      jdbc-url: jdbc:mysql://localhost:3306/springboot-dev?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
    secondary:
      jdbc-url: jdbc:mysql://localhost:3306/springboot-pro?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver