spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  profiles:
    active: dev

  mail:
    host: smtp.qq.com #发送邮件服务器
    username: 1468735157@qq.com #QQ邮箱
    password: azljyoyeafkwiaeg #客户端授权码
    protocol: smtp #发送邮件协议
    properties.mail.smtp.auth: true
    properties.mail.smtp.port: 465 #端口号465或587
    properties.mail.display.sendmail: zimug #可以任意
    properties.mail.display.sendname: Spring Boot Guide Email #可以任意
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8

mail:
  fromMail:
    addr: 1468735157@qq.com
  receptionMail:
    addr: 18255558531@163.com

jasypt:
  encryptor:
    password: root

#    1. 一个家庭有爸爸、妈妈、孩子。
#    2. 这个家庭有一个名字（family-name）叫做“happy family”
#    3. 爸爸有名字(name)和年龄（age）两个属性
#    4. 妈妈有两个别名
#    5. 孩子除了名字(name)和年龄（age）两个属性，还有一个friends的集合
#    6. 每个friend有两个属性：hobby(爱好)和性别(sex)

#family:
#  family-name: "happy \n family"
#  father:
#    name: zimug
#    age: 17
#  mother:
#    alias:
#      - lovly
#      - alice
#  child:
#    name: kobe
#    age: ${family.father.age:5}
#    friends:
#      - hobby: football
#        sex: male
#      - hobby: baskball
#        sex: female